pipeline {
    environment {
        MESSAGE="Hello World"
    }

    stages {
        stage( MESSAGE ) {
            steps {
                script {
                    echo "${MESSAGE}"
                }
            }
        }
    }
}
